apiVersion: v1
kind: Service
metadata:
  name: tango-restendpoint
spec:
  type: NodePort  # Change to LoadBalancer if you need external access
  ports:
    - port: 8080         # The port that will be exposed
      targetPort: 8080   # The port your application listens on
      nodePort: 30080
      #protocol: TCP
  selector:
    app: tango-restendpoint  # Match labels for the pods to route traffic
